### PR TITLE
Refactor the `Validation::IsValidUTF8()` method

### PR DESCRIPTION
**Pull request by lpinca**
This patch simplifies the C++ code taking advantage of the [routine](https://www.cl.cam.ac.uk/%7Emgk25/ucs/utf8_check.c) written by Markus Kuhn.

### CODE REVIEW

**Comment by lpinca** [comment]
This also makes the validation ~2x faster:

Before

```
10000 roundtrips of 64 B text data:	1.5s	421.78 KiB/s
5000 roundtrips of 16 KiB text data:	2.9s	27.25 MiB/s
1000 roundtrips of 128 KiB text data:	3.9s	32.02 MiB/s
100 roundtrips of 1 MiB text data:	2.6s	38 MiB/s
```

After

```
10000 roundtrips of 64 B text data:	1.5s	412.68 KiB/s
5000 roundtrips of 16 KiB text data:	1.4s	56.69 MiB/s
1000 roundtrips of 128 KiB text data:	1.5s	81.32 MiB/s
100 roundtrips of 1 MiB text data:	1.5s	65.32 MiB/s
```

**Comment by lpinca** [comment]
As discussed in https://github.com/websockets/utf-8-validate/pull/32#issuecomment-258422921 this could be optimized further but for now I'm happy with it as is.

@websockets/admin if you can, please take a look. If there are no objections I will merge this and https://github.com/websockets/utf-8-validate/pull/33 and cut a new major version.

Technically there are no breaking changes, but I'm not sure if this catches all the cases that were previously handled so bumping the major version makes more sense.

**Comment by 3rd-Eden** [comment]
@lpinca As long as it passes the autobahn tests with this validation change, i would see no objection.

**Comment by lpinca** [comment]
I'm pretty sure it does. I'll run the Autobahn test suite with this later to be 100% sure.

**Comment by lpinca** [comment]
All tests in the Autobahn test suite passed, merging.

**Pull request merged**
